// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// match_schools_batch_cpp
List match_schools_batch_cpp(CharacterVector names1, CharacterVector groups1, CharacterVector names2, CharacterVector groups2, double threshold_jw_min, double threshold_jw, double exact_jw, double soundex_cosine_thresh);
RcppExport SEXP _tidyschoolvax_match_schools_batch_cpp(SEXP names1SEXP, SEXP groups1SEXP, SEXP names2SEXP, SEXP groups2SEXP, SEXP threshold_jw_minSEXP, SEXP threshold_jwSEXP, SEXP exact_jwSEXP, SEXP soundex_cosine_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type names1(names1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type groups1(groups1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names2(names2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type groups2(groups2SEXP);
    Rcpp::traits::input_parameter< double >::type threshold_jw_min(threshold_jw_minSEXP);
    Rcpp::traits::input_parameter< double >::type threshold_jw(threshold_jwSEXP);
    Rcpp::traits::input_parameter< double >::type exact_jw(exact_jwSEXP);
    Rcpp::traits::input_parameter< double >::type soundex_cosine_thresh(soundex_cosine_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(match_schools_batch_cpp(names1, groups1, names2, groups2, threshold_jw_min, threshold_jw, exact_jw, soundex_cosine_thresh));
    return rcpp_result_gen;
END_RCPP
}
// score_candidates_cpp
DataFrame score_candidates_cpp(std::string name1, CharacterVector names2);
RcppExport SEXP _tidyschoolvax_score_candidates_cpp(SEXP name1SEXP, SEXP names2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name1(name1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names2(names2SEXP);
    rcpp_result_gen = Rcpp::wrap(score_candidates_cpp(name1, names2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidyschoolvax_match_schools_batch_cpp", (DL_FUNC) &_tidyschoolvax_match_schools_batch_cpp, 8},
    {"_tidyschoolvax_score_candidates_cpp", (DL_FUNC) &_tidyschoolvax_score_candidates_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidyschoolvax(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
