# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Match school names across two datasets using vectorised C++ distances
#'
#' Replaces the per-row R loop in \code{match_schools_names()}.  For every
#' row in \code{data1} it finds candidate rows in \code{data2} that share
#' the same group key (typically \code{county_std}), then classifies each
#' data1 row as:
#' \describe{
#'   \item{0}{No data2 rows share the same group key.}
#'   \item{1}{Unmatched: all JW distances exceed \code{threshold_jw_min}.}
#'   \item{2}{Exact: at least one JW distance ≤ \code{exact_jw}. The
#'     returned candidates are all rows with JW ≤ \code{exact_jw}.}
#'   \item{3}{Non-exact candidates: after filtering by
#'     \code{(jw <= threshold_jw) | (soundex == 0 & cosine <= soundex_cosine_thresh)},
#'     the top-10 (by JW) are returned for R-level detailed scoring.}
#' }
#'
#' @param names1  Character vector — \code{school_name_std} for all data1 rows.
#' @param groups1 Character vector — composite group key (lowercase) for data1.
#' @param names2  Character vector — \code{school_name_std} for all data2 rows.
#' @param groups2 Character vector — composite group key (lowercase) for data2.
#' @param threshold_jw_min Numeric. Rows where all JW distances exceed this
#'   value are classified as unmatched (status 1).
#' @param threshold_jw Numeric. JW threshold for candidate selection.
#' @param exact_jw Numeric. JW threshold for classifying a match as exact
#'   (status 2).
#' @param soundex_cosine_thresh Numeric. Cosine threshold used alongside
#'   \code{soundex == 0} in the fallback candidate filter (default 0.25).
#'
#' @return A named list with elements:
#' \describe{
#'   \item{status}{Integer vector (length = \code{length(names1)}).}
#'   \item{candidates_idx}{List of integer vectors: 1-based indices into
#'     \code{names2}.}
#'   \item{candidates_jw}{List of numeric vectors: JW distances.}
#'   \item{candidates_soundex}{List of numeric vectors: Soundex distances
#'     (0 or 1). \code{NULL} for exact-match rows.}
#'   \item{candidates_cosine}{List of numeric vectors: Cosine distances.
#'     \code{NULL} for exact-match rows.}
#' }
#' @keywords internal
match_schools_batch_cpp <- function(names1, groups1, names2, groups2, threshold_jw_min, threshold_jw, exact_jw, soundex_cosine_thresh = 0.25) {
    .Call('_tidyschoolvax_match_schools_batch_cpp', PACKAGE = 'tidyschoolvax', names1, groups1, names2, groups2, threshold_jw_min, threshold_jw, exact_jw, soundex_cosine_thresh)
}

