# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_schools_batch_cpp <- function(names1, groups1, names2, groups2, threshold_jw_min, threshold_jw, exact_jw, soundex_cosine_thresh = 0.25) {
    .Call(`_tidyschoolvax_match_schools_batch_cpp`, names1, groups1, names2, groups2, threshold_jw_min, threshold_jw, exact_jw, soundex_cosine_thresh)
}
