# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Match school names across two datasets using vectorised C++ distances
#'
#' Replaces the per-row R loop in \code{match_schools_names()}.  For every
#' row in \code{data1} it finds candidate rows in \code{data2} that share
#' the same group key (typically \code{county_std}), then classifies each
#' data1 row as:
#' \describe{
#'   \item{0}{No data2 rows share the same group key.}
#'   \item{1}{Unmatched: all JW distances exceed \code{threshold_jw_min}.}
#'   \item{2}{Exact: at least one JW distance ≤ \code{exact_jw}. The
#'     returned candidates are all rows with JW ≤ \code{exact_jw}.}
#'   \item{3}{Non-exact candidates: after filtering by
#'     \code{(jw <= threshold_jw) | (soundex == 0 & cosine <= soundex_cosine_thresh)},
#'     the top-10 (by JW) are returned for R-level detailed scoring.}
#' }
#'
#' @param names1  Character vector — \code{school_name_std} for all data1 rows.
#' @param groups1 Character vector — composite group key (lowercase) for data1.
#' @param names2  Character vector — \code{school_name_std} for all data2 rows.
#' @param groups2 Character vector — composite group key (lowercase) for data2.
#' @param threshold_jw_min Numeric. Rows where all JW distances exceed this
#'   value are classified as unmatched (status 1).
#' @param threshold_jw Numeric. JW threshold for candidate selection.
#' @param exact_jw Numeric. JW threshold for classifying a match as exact
#'   (status 2).
#' @param soundex_cosine_thresh Numeric. Cosine threshold used alongside
#'   \code{soundex == 0} in the fallback candidate filter (default 0.25).
#'
#' @return A named list with elements:
#' \describe{
#'   \item{status}{Integer vector (length = \code{length(names1)}).}
#'   \item{candidates_idx}{List of integer vectors: 1-based indices into
#'     \code{names2}.}
#'   \item{candidates_jw}{List of numeric vectors: JW distances.}
#'   \item{candidates_soundex}{List of numeric vectors: Soundex distances
#'     (0 or 1). \code{NULL} for exact-match rows.}
#'   \item{candidates_cosine}{List of numeric vectors: Cosine distances.
#'     \code{NULL} for exact-match rows.}
#' }
#' @keywords internal
match_schools_batch_cpp <- function(names1, groups1, names2, groups2, threshold_jw_min, threshold_jw, exact_jw, soundex_cosine_thresh = 0.25) {
    .Call('_tidyschoolvax_match_schools_batch_cpp', PACKAGE = 'tidyschoolvax', names1, groups1, names2, groups2, threshold_jw_min, threshold_jw, exact_jw, soundex_cosine_thresh)
}

#' Compute all string-distance metrics between one query name and multiple candidates
#'
#' Computes OSA, Q-gram (q=1), Cosine (q=1), Jaccard (q=1), Jaro-Winkler, and
#' Soundex distances between \code{name1} and each element of \code{names2},
#' replicating the metrics computed by
#' \code{stringdist::stringdist(method = c("osa","qgram","cosine","jaccard","jw","soundex"))}.
#' Used internally by \code{match_locations()}.
#'
#' @param name1  Single query string (pre-standardised, lowercase).
#' @param names2 Character vector of candidate strings (pre-standardised).
#'
#' @return A \code{data.frame} with one row per element of \code{names2} and
#'   columns \code{name}, \code{osa} (integer), \code{qgram} (integer),
#'   \code{cosine}, \code{jaccard}, \code{jw}, \code{soundex}, \code{score_sums}.
#' @keywords internal
score_candidates_cpp <- function(name1, names2) {
    .Call('_tidyschoolvax_score_candidates_cpp', PACKAGE = 'tidyschoolvax', name1, names2)
}

#' Compute pairwise Jaro-Winkler distance matrix
#'
#' Returns the full n-by-n symmetric matrix of Jaro-Winkler distances for a
#' character vector of pre-standardised school names.  Used by
#' \code{fuzzy_match_unmatched_schools()} to replace a nested R for-loop.
#'
#' @param names Character vector of strings.
#' @return A numeric matrix (n x n, symmetric, zero diagonal) of JW distances.
#' @keywords internal
pairwise_jw_cpp <- function(names) {
    .Call('_tidyschoolvax_pairwise_jw_cpp', PACKAGE = 'tidyschoolvax', names)
}

